package com.miao.codescanner;
import android.Manifest;import android.app.Activity;import android.os.Bundle;import android.print.PrintManager;import android.content.Context;import android.content.pm.PackageManager;import android.webkit.PermissionRequest;import android.webkit.WebChromeClient;import android.webkit.WebView;import android.webkit.WebViewClient;import android.webkit.WebSettings;import android.webkit.JavascriptInterface;import android.os.Build;import androidx.webkit.WebViewAssetLoader;import androidx.webkit.WebViewClientCompat;import android.webkit.WebResourceRequest;import android.webkit.WebResourceResponse;
public class MainActivity extends Activity {
 WebView view; PermissionRequest pending;
 @Override public void onCreate(Bundle state){super.onCreate(state);view=new WebView(this);setContentView(view);WebSettings s=view.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);view.addJavascriptInterface(new Object(){@JavascriptInterface public void print(){runOnUiThread(()->{PrintManager pm=(PrintManager)getSystemService(Context.PRINT_SERVICE);pm.print("扫码标签",view.createPrintDocumentAdapter("扫码标签"),null);});}},"AndroidPrint");WebViewAssetLoader loader=new WebViewAssetLoader.Builder().addPathHandler("/assets/",new WebViewAssetLoader.AssetsPathHandler(this)).build();view.setWebViewClient(new WebViewClientCompat(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest request){return loader.shouldInterceptRequest(request.getUrl());}});view.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest request){runOnUiThread(()->{if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){pending=request;requestPermissions(new String[]{Manifest.permission.CAMERA},42);}else grantCamera(request);});}});view.loadUrl("https://appassets.androidplatform.net/assets/index.html"); }
 private void grantCamera(PermissionRequest r){for(String resource:r.getResources())if(PermissionRequest.RESOURCE_VIDEO_CAPTURE.equals(resource)){r.grant(new String[]{resource});return;}r.deny();}
 @Override public void onRequestPermissionsResult(int code,String[] permissions,int[] results){super.onRequestPermissionsResult(code,permissions,results);if(code==42&&pending!=null){if(results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)grantCamera(pending);else pending.deny();pending=null;}}
 @Override public void onBackPressed(){if(view.canGoBack())view.goBack();else super.onBackPressed();}
}
